#
# Site settings ******************************************
#

title: sionta.
description: >- # this means to ignore newlines until "baseurl:"
  A brief description of my website

baseurl: "" # the subpath of your site, e.g. "/blog" (DON'T include a trailing slash)
url: "" # the base hostname & protocol for your site, e.g. "http://example.com"
google_analytics: G-31WRW155T4

timezone: Asia/Tokyo
lang: en

image: "/assets/img/avatar.svg" # https://github.com/sionta.png?size=100
# Set to `true` to enable site logo in header and "image:" is required.
enable_logo: false

# Generate social links
social_links:
  - { platform: github, url: "https://github.com/sionta" }
  - { platform: mastodon, url: "https://mastodon.social/@sionta" }
  - { platform: twitter, url: "https://twitter.com/r007mmxv" }

#
# Post settings ******************************************
#

author:
  avatar: "/assets/img/avatar.svg"
  name: Andre Attamimi
  twitter: R007MMXV
  url: https://github.com/sionta

# The default value is "%b %d, %Y" (e.g. Nov 14, 2023)
# Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
date_format: "%b %d, %Y"

comments:
  provider: "giscus" # e.g. "disqus" and the provider settings below:
  disqus:
    # https://help.disqus.com/en/articles/1717111-what-s-a-shortname
    shortname: "andreattamimi"
  giscus:
    # For more setting refer to https://giscus.app/
    repo: "sionta/blog" # e.g. "owner/repo"
    repo_id: "R_kgDOLxRA-w"
    category: "Q&A"
    category_id: "DIC_kwDOLxRA-84CfGPN"
  utterances:
    # https://utteranc.es/
    repo: "sionta/blog" # e.g. "owner/repo"
    issue_term: "pathname"

#
# Build settings *****************************************
#

# https://github.com/jekyll/jekyll-feed
feed:
  posts_limit: 10
  excerpt_only: false

# https://github.com/toshimaru/jekyll-toc
toc:
  min_level: 2
  max_level: 4
  ordered_list: false
  list_id: toc
  list_class: toc-list
  sublist_class: ""
  item_class: toc-item
  item_prefix: toc-

# https://jch.penibelst.de/
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []

# https://sass-lang.com/documentation/cli/ruby-sass/
sass:
  style: compressed
  # style: expanded # better for test in local

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
  math_engine: katex
  math_engine_opts: {}

# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled: [categories, tags]
  layout: archive
  permalinks:
    tag: "/tags/:name/"
    category: "/categories/:name/"

collections:
  redirects:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: redirects
    values:
      layout: page
      permalink: "/:title/"
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: "/blog/:title/"

exclude:
  - "*.gem"
  - "*.gemspec"
  - "*.lock"
  - "test*"
  - "tool*"
  - "package*.json"
  - "screenshot*"
  - "README*"
