# Site settings
title: sionta
description: >-
  A brief description of your website

url: "https://andreattamimi.com"
baseurl: ""
logo: "/assets/img/avatar.png" # https://github.com/sionta.png?size=100

timezone: Asia/Tokyo
lang: en

google_analytics: G-31WRW155T4

author:
  name: Andre Attamimi
  email: info@andreattamimi.com
  url: https://github.com/sionta

twitter:
  username: R007MMXV

# Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
date_format: "%B %d, %Y"

# Set to `true` to show excerpts on the homepage.
show_excerpts: true

# Comments Settings
comments:
  provider: "" # (e.g., "disqus")
  # The provider setting below:
  disqus: # Disqus > https://help.disqus.com/en/articles/1717111-what-s-a-shortname
    shortname: "andreattamimi"
  giscus: # giscus > https://giscus.app/
    repo: "sionta/blog" # (e.g., "owner/repo")
    repo_id: "R_kgDOLxRA-w"
    category: "Q&A"
    category_id: "DIC_kwDOLxRA-84CfGPN"
  utterances: # utterances > https://utteranc.es/
    repo: "sionta/blog" # (e.g., "owner/repo")
    issue_term: "pathname"

social_links:
  - { platform: github, user_url: "https://github.com/sionta" }
  - { platform: mastodon, user_url: "https://mastodon.social/@sionta" }
  - { platform: twitter, user_url: "https://twitter.com/r007mmxv" }
  # - { platform: x, user_url: "https://x.com/r007mmxv" }
  - {
      platform: linkedin,
      user_url: "https://www.linkedin.com/in/andreattamimi",
    }

# Development settings =======================================
feed:
  posts_limit: 5
  excerpt_only: false

kramdown:
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
  math_engine: katex
  math_engine_opts: {}

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      permalink: "/blog/:title/"

jekyll-archives:
  enabled: ["categories", "tags"]
  layouts:
    category: "category"
    tag: "tag"
  permalinks:
    tag: "/tags/:name/"
    category: "/categories/:name/"

sass:
  # style: "compressed"
  sourcemap: never

compress_html:
  clippings: "all"
  comments: "all"
  endings: "all"
  profile: false
  blanklines: false
  ignore:
    envs: # ["development"]

exclude:
  - "*.gem"
  - "*.gemspec"
  - "*.lock"
  - "package*.json"
  - "screenshot*"
  - "README*"
