title: sionta.
description: >-
  A brief description of my website

url: ""
baseurl: "" # DON'T include a trailing slash!

google_analytics: G-31WRW155T4
timezone: Asia/Tokyo
lang: en

logo: "/assets/img/avatar.png" # https://github.com/sionta.png?size=100

author:
  name: Andre Attamimi
  email: info@andreattamimi.com
  url: https://github.com/sionta
twitter:
  username: R007MMXV

# Set to `true` to enable progressive web apps.
enable_pwa: false

# Set to `true` to show excerpts the post list.
show_excerpts: true

# The default value is "%b %d, %Y" (e.g. Nov 14, 2023)
# Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
date_format: "%b %d, %Y"

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
# header_pages:
#   - pages/about.md

# Generate social links, for the platform icons available at `_includes/social-icons`.
social_links:
  - { platform: github, user_url: "https://github.com/sionta" }
  - { platform: mastodon, user_url: "https://mastodon.social/@sionta" }
  - { platform: twitter, user_url: "https://twitter.com/r007mmxv" }

feed:
  posts_limit: 5
  excerpt_only: false

# Development settings =======================================
sass:
  style: compressed

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      permalink: "/blog/:title/"

markdown: kramdown
kramdown:
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
  math_engine: katex
  math_engine_opts: {}

exclude:
  - "*.gem"
  - "*.gemspec"
  - "*.lock"
  - "tools"
  - "package*.json"
  - "screenshot*"
  - "README*"
