#
# Site settings ******************************************
#

title: Andre Attamimi
brand: Andre S. Attamimi # alternative site name for animation
description: >- # this means to ignore newlines until "baseurl:"
  run, study, modify, and share

baseurl: "" # the subpath of your site, e.g. "/blog" (DON'T include a trailing slash)
url: "" # the base hostname & protocol for your site, e.g. "http://example.com"

timezone: Asia/Tokyo
lang: en

image: "/assets/img/avatar.svg" # https://github.com/sionta.png?size=100
twitter:
  username: R007MMXV

google_analytics: G-31WRW155T4

# Generate social links in footer. for available platforms see "includes/social-item".
social_links:
  - { platform: github, user_url: "https://github.com/sionta" }
  - { platform: mastodon, user_url: "https://mastodon.social/@sionta" }
  - { platform: twitter, user_url: "https://twitter.com/r007mmxv" }

color_scheme: auto # dark, light

#
# Post settings ******************************************
#

banner: "https://placehold.co/600x400?text=Hello+World/"

author:
  picture: "/assets/img/avatar.svg"
  name: Andre Attamimi
  twitter: R007MMXV
  email: info@andreattamimi.com
  url: https://github.com/sionta

# Set to `true` to show excerpts on the homepage.
show_excerpts: false

# The default value is "%b %d, %Y" (e.g. Nov 14, 2023)
# Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
date_format: "%b %d, %Y"

comments:
  provider: "giscus" # e.g. "disqus". The provider settings below:
  disqus:
    # What is `shortname` refer to https://help.disqus.com/en/articles/1717111-what-s-a-shortname
    shortname: "andreattamimi"
  giscus:
    # For more setting refer to https://giscus.app/
    repo: "sionta/blog" # e.g. "owner/repo"
    repo_id: "R_kgDOLxRA-w"
    category: "Q&A"
    category_id: "DIC_kwDOLxRA-84CfGPN"
  utterances:
    # For more setting refer to https://utteranc.es/
    repo: "sionta/blog" # e.g. "owner/repo"
    issue_term: "pathname"

#
# Build settings *****************************************
#

# https://github.com/jekyll/jekyll-paginate
paginate: 3
paginate_path: "/blog/page:num/"

# https://github.com/jekyll/jekyll-feed
feed:
  posts_limit: 10
  excerpt_only: false

# https://github.com/jekyll/jekyll-gist
gist:
  noscript: false

# https://sass-lang.com/documentation/cli/ruby-sass/
sass:
  style: compressed
  # style: expanded # for development

# https://jekyllrb.com/docs/configuration/markdown/
markdown: kramdown
kramdown:
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    default_lang: plain
    # span:
    #   line_numbers: false
    # block:
    #   line_numbers: true
    #   start_line: 1
  math_engine: katex
  math_engine_opts: {}

# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag
  permalinks:
    tag: "/tags/:name/"

collections:
  pages:
    output: true
    permalink: "/:name/"
  posts:
    output: true
    permalink: "/blog/:title/"

defaults:
  - scope:
      path: _pages
      type: pages
    values:
      layout: page
  - scope:
      path: _posts
      type: posts
    values:
      layout: post

exclude:
  - "*.gem"
  - "*.gemspec"
  - "*.lock"
  - "docs"
  - "tests"
  - "tools"
  - "package*.json"
  - "README.md"
