# SITE SETTINGS ******************************************
title: Andre Attamimi
description: >-
  run, study, modify, and share.
url: "" # the base hostname & protocol of the site (e.g. http://example.com)
baseurl: "" # if deploy in github-pages the subpath of the site (e.g. /blog)

timezone: Asia/Tokyo

# Web Analytics
analytics:
  google:
    id: "G-31WRW155T4" # fill in your Google Analytics ID
  cloudflare:
    id: "" # fill in your Cloudflare Web Analytics token
  goatcounter:
    id: "" # fill in your GoatCounter ID
  umami:
    id: "" # fill in your Umami ID
    domain: "" # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain

# Web verifications
verifications:
  google: ""
  bing: ""
  yandex: ""
  pinterest: ""
  facebook: ""

author:
  name: Andre Attamimi
  twitter: r007mmxv
  url: https://github.com/sionta
  picture: /assets/img/avatar.png

# The default value is %b %d, %Y (e.g. Nov 14, 2023)
# Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
date_format: "%b %d, %Y"

# Generate social links. Icon use Tabler https://tabler.io/icons
social_links:
  - { name: Subcribe, icon: rss, url: feed.xml }
  - { name: Email, icon: mail, url: mailto:info@andreattamimi.com }
  - { name: GitHub, url: https://github.com/sionta }
  - { name: Mastodon, url: https://mastodon.social/@sionta }
  - { name: Twitter, url: https://twitter.com/r007mmxv }

# Post comments
comments:
  provider: disqus # (e.g. giscus)
  # The provider settings below:
  disqus:
    # What is `shortname` see https://help.disqus.com/en/articles/1717111-what-s-a-shortname
    shortname: andreattamimi
  giscus:
    # For more settings see https://giscus.app/
    repo: sionta/blog # e.g. sionta/blog
    repo_id: R_kgDOLxRA-w
    category: Q&A
    category_id: DIC_kwDOLxRA-84CfGPN
  utterances:
    # For more setting see to https://utteranc.es/
    repo: sionta/blog # e.g. sionta/blog
    label: Q&A
    issue_term: pathname

paginate: 6
paginate_path: /blog/:num/

self_host: development # `production` or `development`

# IMPORTANT SETTINGS *****************************************
sass:
  style: expanded
  sourcemap: development

# Options minify css and `_plugins/minify.rb`
# if set `true` running on development and production.
minify:
  html: true
  css: production
  js: true

# https://jekyllrb.com/docs/collections/
collections:
  menus: # navigation pages
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /blog/:title/

# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  - scope:
      path: _menus
      type: menus
    values:
      layout: page
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      toc: false
      comments: false
      mermaid: false
      math: "" # or mathjax, if set to `true` math enable use katex

# https://jekyllrb.com/docs/configuration/markdown/
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1
      table_class: rouge-table # - a CSS class for the table
      gutter_class: rouge-gutter # - a CSS class for the line-number cell
      code_class: rouge-code # - a CSS class for the code cell

exclude:
  - /docs
  - /tests
  - /tools
  - /scripts
  - package*.json
  - LICENSE
  - README.md
