title: sionta.
description: >-
  A brief description of my website

url: ""
baseurl: "" # DON'T include a trailing slash!

google_analytics: G-31WRW155T4
timezone: Asia/Tokyo
lang: en

# Site logo for SEO
logo: "/assets/img/avatar.png" # https://github.com/sionta.png?size=100
enable_logo: false # enable logo in site header

author:
  name: Andre Attamimi
  email: info@andreattamimi.com
  url: https://github.com/sionta
twitter:
  username: R007MMXV

# Set to `true` to enable progressive web apps.
enable_pwa: false

# Set to `true` to show excerpts the post list.
show_excerpts: true

# The default value is "%b %d, %Y" (e.g. Nov 14, 2023)
# Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
date_format: "%b %d, %Y"

# Comments Settings
comments:
  provider: "giscus" # (e.g., "disqus")
  # The provider setting below:
  disqus: # Disqus > https://help.disqus.com/en/articles/1717111-what-s-a-shortname
    shortname: "andreattamimi"
  giscus: # giscus > https://giscus.app/
    repo: "sionta/blog" # (e.g., "owner/repo")
    repo_id: "R_kgDOLxRA-w"
    category: "Q&A"
    category_id: "DIC_kwDOLxRA-84CfGPN"
  utterances: # utterances > https://utteranc.es/
    repo: "sionta/blog" # (e.g., "owner/repo")
    issue_term: "pathname"

# navigation:
#   - name: Home
#     link: /
#   - name: About
#     link: /about/
#   - name: RSS
#     link: /feed.xml
#     icon: rss
#   - name: GitHub
#     link: https://github.com/sionta
#     external_icon: true

# Generate social links, for the platform icons available at `_includes/social-icons`.
social_links:
  - { platform: github, user_url: "https://github.com/sionta" }
  - { platform: mastodon, user_url: "https://mastodon.social/@sionta" }
  - { platform: twitter, user_url: "https://twitter.com/r007mmxv" }

feed:
  posts_limit: 5
  excerpt_only: false

# paginate: 5
# paginate_path: "/page:num/"

jekyll-archives:
  enabled: [categories, tags]
  layout: archive
  permalinks:
    tag: "/tags/:name/"
    category: "/categories/:name/"

# Development settings =======================================
sass:
  style: compressed

# prettier-ignore
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []

collections:
  pages:
    output: true
    sort_by: order

defaults:
  - scope:
      path: _pages
      type: pages
    values:
      layout: page
      permalink: "/:title/"
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      permalink: "/blog/:title/"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
  math_engine: katex
  math_engine_opts: {}

exclude:
  - "*.gem"
  - "*.gemspec"
  - "*.lock"
  - "test*"
  - "tool*"
  - "package*.json"
  - "screenshot*"
  - "README*"
