# Site settings
title: "sionta"
author: "Andre Attamimi"
description: "A brief description of your website"
url: ""
# baseurl: "/blog"
email: ""
lang: "en"

# Post settings
# avatar: "https://github.com/sionta.png?size=100"
avatar: "/assets/images/favicon.png"

# Set to `true` to show excerpts on the homepage.
show_excerpts: false

# Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
date_format: "%b-%d-%Y"

# Development settings =======================================
sass:
  style: compressed
  # style: expanded
  sourcemap: never

kramdown:
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter: "rouge"
  syntax_highlighter_opts:
    css_class: "highlight"
  math_engine: katex
  math_engine_opts: {}

compress_html:
  profile: false
  clippings: all
  endings: all
  startings: [html, head, body]
  comments: ["<!-- ", " -->"]
  # ignore:
  #   envs: ["development"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/posts/:title/"
