# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings ******************************************
title: Andre Attamimi
brand: Andre S. Attamimi # alternative site name for animation
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  run, study, modify, and share.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: G-31WRW155T4

timezone: Asia/Tokyo
lang: en

image: "/assets/img/avatar.svg" # https://github.com/sionta.png?size=100
twitter:
  username: R007MMXV

author:
  picture: "/assets/img/avatar.svg"
  name: Andre Attamimi
  twitter: R007MMXV
  email: info@andreattamimi.com
  url: https://github.com/sionta

# Set to `true` to show excerpts on the homepage.
show_excerpts: false

# The default value is "%b %d, %Y" (e.g. Nov 14, 2023)
# Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
date_format: "%b %d, %Y"

paginate: 5
paginate_path: "/blog/page:num/"

comments:
  provider: "" # e.g. "disqus".
  # The provider by settings below:
  disqus:
    # What is `shortname` refer to https://help.disqus.com/en/articles/1717111-what-s-a-shortname
    shortname: "andreattamimi"
  giscus:
    # For more setting refer to https://giscus.app/
    repo: "sionta/blog" # e.g. "owner/repo"
    repo_id: "R_kgDOLxRA-w"
    category: "Q&A"
    category_id: "DIC_kwDOLxRA-84CfGPN"
  utterances:
    # For more setting refer to https://utteranc.es/
    repo: "sionta/blog" # e.g. "owner/repo"
    issue_term: "pathname"

# Build settings *****************************************
# https://github.com/jekyll/jekyll-feed
feed:
  posts_limit: 10
  excerpt_only: false

# https://github.com/jekyll/jekyll-gist
gist:
  noscript: false

# https://sass-lang.com/documentation/cli/ruby-sass/
sass:
  # style: compressed
  style: expanded # for development

# https://jekyllrb.com/docs/configuration/markdown/
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  pages:
    output: true
    permalink: "/:name/"
  posts:
    output: true
    permalink: "/blog/:title/"

defaults:
  - scope:
      path: _pages
      type: pages
    values:
      layout: page
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      # Special configuration for layout "post":
      toc: false # Table of contents
      anchor: true # Anchor headings
      mermaid: false # Mermaid diagrammings
      comments: false # Comments, first set `site.comments.provider`

exclude:
  - "*.gem"
  - "*.gemspec"
  - "*.lock"
  - "*copy*.*"
  - "/docs"
  - "/test*"
  - "/tool*"
  - "/script*"
  - "package*.json"
  - "README.md"
