title: sionta.
description: >-
  A brief description of my website

url: ""
baseurl: "" # DON'T include a trailing slash!

google_analytics: G-31WRW155T4

timezone: Asia/Tokyo
lang: en

image: "/assets/img/avatar.svg" # https://github.com/sionta.png?size=100
# Set to `true` to enable site logo in header.
enable_logo: false
twitter:
  username: R007MMXV

author:
  picture: "/assets/img/avatar.svg"
  twitter: R007MMXV
  name: Andre Attamimi
  email: info@andreattamimi.com
  url: https://github.com/sionta

# Set to `true` to enable progressive web apps.
enable_pwa: false

# Set to `true` to show excerpts the post list.
show_excerpts: true

# The default value is "%b %d, %Y" (e.g. Nov 14, 2023)
# Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
date_format: "%b %d, %Y"

# Comments Settings
comments:
  provider: "giscus" # (e.g., "disqus")
  # The provider setting below:
  disqus: # https://help.disqus.com/en/articles/1717111-what-s-a-shortname
    shortname: "andreattamimi"
  giscus: # https://giscus.app/
    repo: "sionta/blog" # (e.g., "owner/repo")
    repo_id: "R_kgDOLxRA-w"
    category: "Q&A"
    category_id: "DIC_kwDOLxRA-84CfGPN"
  utterances: # https://utteranc.es/
    repo: "sionta/blog" # (e.g., "owner/repo")
    issue_term: "pathname"

# Generate social links
social_links:
  - { platform: github, url: "https://github.com/sionta" }
  - { platform: mastodon, url: "https://mastodon.social/@sionta" }
  - { platform: twitter, url: "https://twitter.com/r007mmxv" }

# Development settings =======================================

# https://github.com/jekyll/jekyll-feed
feed:
  posts_limit: 10
  excerpt_only: false

# https://github.com/toshimaru/jekyll-toc
toc:
  min_level: 2
  max_level: 5
  ordered_list: false
  list_id: toc
  list_class: toc-list
  sublist_class: ""
  item_class: toc-item
  item_prefix: toc-

# https://jch.penibelst.de/
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []

sass:
  style: compressed

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
  math_engine: katex
  math_engine_opts: {}

# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled: [categories, tags]
  layout: archive
  permalinks:
    tag: "/tags/:name/"
    category: "/categories/:name/"

collections:
  partials:
    output: true
    sort_by: order

defaults:
  - scope:
      path: _partials
      type: partials
    values:
      layout: page
      permalink: "/:title/"
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      permalink: "/blog/:title/"

exclude:
  - "*.gem"
  - "*.gemspec"
  - "*.lock"
  - "test*"
  - "tool*"
  - "package*.json"
  - "screenshot*"
  - "README*"
