# SITE SETTINGS ******************************************
title: "Andre Attamimi"
description: >-
  run, study, modify, and share.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

# Site Verifications. NOTE: if you this on private build
site_verification:
  google: ""
  bing: ""
  yandex: ""
  pinterest: ""
  facebook: ""

# Web Analytics
web_analytics:
  google:
    id: "G-31WRW155T4" # fill in your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token

# The default value is "%b %d, %Y" (e.g. Nov 14, 2023)
# Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
date_format: ""

# Generate social links. Icon use Tabler https://tabler.io/icons
social_links:
  - { title: Email, icon: mail, url: "mailto:info@andreattamimi.com" }
  - { title: GitHub, url: "https://github.com/sionta" }
  - { title: Mastodon, url: "https://mastodon.social/@sionta" }
  - { title: Twitter, url: "https://twitter.com/r007mmxv" }

comments:
  provider: "giscus" # e.g. "disqus".
  # The provider by settings below:
  disqus:
    # What is `shortname` see https://help.disqus.com/en/articles/1717111-what-s-a-shortname
    shortname: "andreattamimi"
  giscus:
    # For more settings see https://giscus.app/
    repo: "sionta/blog" # e.g. "owner/repo"
    repo_id: "R_kgDOLxRA-w"
    category: "Q&A"
    category_id: "DIC_kwDOLxRA-84CfGPN"
  utterances:
    # For more setting see to https://utteranc.es/
    repo: "sionta/blog" # e.g. "owner/repo"
    issue_term: "pathname"

paginate: 5
paginate_path: "/blog/page:num/"
