#
# Site settings ******************************************
#

title: sionta
description: >- # this means to ignore newlines until "baseurl:"
  run, study, modify, and share

baseurl: "" # the subpath of your site, e.g. "/blog" (DON'T include a trailing slash)
url: "" # the base hostname & protocol for your site, e.g. "http://example.com"
google_analytics: G-31WRW155T4

timezone: Asia/Tokyo
lang: en

image: "/assets/img/avatar.svg" # https://github.com/sionta.png?size=100
# Set to `true` to enable site logo in header and "image:" is required.
enable_logo: false

twitter:
  username: R007MMXV

# Generate social links in footer. for available platforms see "includes/social-item".
social_links:
  - { platform: github, user_url: "https://github.com/sionta" }
  - { platform: mastodon, user_url: "https://mastodon.social/@sionta" }
  - { platform: twitter, user_url: "https://twitter.com/r007mmxv" }

#
# Post settings ******************************************
#

author:
  picture: "/assets/img/avatar.svg"
  name: Andre Attamimi
  twitter: R007MMXV
  email: info@andreattamimi.com
  url: https://github.com/sionta

# Set to `true` to show excerpts on the homepage.
show_excerpts: false

# The default value is "%b %d, %Y" (e.g. Nov 14, 2023)
# Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
date_format: "%b %d, %Y"

comments:
  provider: "giscus" # e.g. "disqus". The provider settings below:
  disqus:
    # What is `shortname` refer to https://help.disqus.com/en/articles/1717111-what-s-a-shortname
    shortname: "andreattamimi"
  giscus:
    # For more setting refer to https://giscus.app/
    repo: "sionta/blog" # e.g. "owner/repo"
    repo_id: "R_kgDOLxRA-w"
    category: "Q&A"
    category_id: "DIC_kwDOLxRA-84CfGPN"
  utterances:
    # For more setting refer to https://utteranc.es/
    repo: "sionta/blog" # e.g. "owner/repo"
    issue_term: "pathname"

#
# Build settings *****************************************
#

# https://github.com/jekyll/jekyll-feed
feed:
  posts_limit: 10
  excerpt_only: false

# https://github.com/toshimaru/jekyll-toc
toc:
  min_level: 2
  max_level: 4
  ordered_list: false
  list_id: toc
  list_class: toc-list
  sublist_class: ""
  item_class: toc-item
  item_prefix: toc-

# https://github.com/jekyll/jekyll-gist
gist:
  noscript: false

# https://sass-lang.com/documentation/cli/ruby-sass/
sass:
  # style: compressed
  style: expanded # for development

kramdown:
  hard_wrap: false
  auto_ids: true
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    # default_lang: plain
    # span:
    #   line_numbers: false
    # block:
    #   line_numbers: true
    #   start_line: 1
  math_engine: katex
  math_engine_opts: {}

# https://github.com/jekyll/jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

collections:
  partials:
    output: true
    # sort_by: order

defaults:
  - scope:
      path: ""
      type: partials
    values:
      # layout: [default, base]
      permalink: /:name/
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: "/blog/:title/"

# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled: [categories, tags]
  # layout: archive
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: "/tags/:name/"
    category: "/categories/:name/"

exclude:
  - "*.gem"
  - "*.gemspec"
  - "*.lock"
  - "docs"
  - "tests"
  - "tools"
  - "package*.json"
  - "README.md"
