# Site settings
title: "sionta"
author: "Andre Attamimi"
description: "A brief description of your website"
# avatar: "https://github.com/sionta.png?size=100"
avatar: "/assets/images/favicon.png"
url: ""
baseurl: ""
email: ""
lang: "en"

# Development settings =======================================
sass:
  style: compressed
  # style: expanded
  sourcemap: never

kramdown:
  syntax_highlighter: "rouge"
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: "highlight"
  math_engine: katex
  math_engine_opts: {}

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/posts/:title"
