# Site settings
title: "sionta"
description: "A brief description of your website"
url: "https://andreattamimi.com" # (e.g. "https://example.com")
baseurl: "" # (e.g. /blog) if deploy in GitHub Pages
lang: "en"
google_analytics: "G-31WRW155T4"

# Post settings ==============================================
author:
  name: "Andre Attamimi" # `site.title`
  url: https://github.com/sionta # `site.url`
  email: "info@andreattamimi.com"
  avatar: "/assets/images/favicon.svg" # "https://github.com/sionta.png?size=100"
  github: "sionta"
  twitter: "R007MMXV"
  mastodon: "sionta"
  linkedin: "andreattamimi"

# Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
date_format: "%B %d, %Y"

# Set to `true` to show excerpts on the homepage.
show_excerpts: true

# Comments Settings
comments:
  provider: "utterances" # (e.g., "disqus")
  # The provider setting below:
  disqus: # Disqus > https://help.disqus.com/en/articles/1717111-what-s-a-shortname
    shortname: "andreattamimi"
  giscus: # giscus > https://giscus.app/
    repo: "sionta/blog" # (e.g., "owner/repo")
    repo_id: "R_kgDOLxRA-w"
    category: "Q&A"
    category_id: "DIC_kwDOLxRA-84CfGPN"
  utterances: # utterances > https://utteranc.es/
    repo: "sionta/blog" # (e.g., "owner/repo")
    issue_term: "pathname"
    # theme: "preferred-color-scheme"

# Development settings =======================================
sass:
  style: "compressed"
  # style: "expanded"
  sourcemap: "never"

kramdown:
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter: "rouge"
  syntax_highlighter_opts:
    css_class: "highlight"
  math_engine: "katex"
  math_engine_opts: {}

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/posts/:title/"

# compress_html:
#   clippings: "all"
#   comments: "all"
#   endings: "all"
#   profile: false
#   blanklines: false
#   ignore:
#     envs: ["development"]

feed:
  posts_limit: 3
  excerpt_only: true
  tags: true
  # categories:
  #   - tutorial
  #   - updates

jekyll-archives:
  enabled: ["categories", "tags"]
  layouts:
    category: "category"
    tag: "tag"
  permalinks:
    tag: "/tags/:name/"
    category: "/categories/:name/"

exclude:
  - "*.gem"
  - "*.gemspec"
  - "test*"
  - "screenshot*"
  - "node_modules"
  - "netlify.toml"
  - "README.md"
  - "yarn.lock"
  - "package*.json"
