#!/usr/bin/env bash

set -eu

if [ -f '../Gemfile' ]; then
  ROOT="$PWD/.."
elif [ -f 'Gemfile' ]; then
  ROOT="$PWD"
else
  echo "Gemfile not found. Exiting."
  exit 1
fi

cd "$ROOT"

TOOLS=("csso" "html-minifier" "uglifyjs")
export PATH="$ROOT/node_modules/.bin:$PATH"

check() {
  for tool in "${TOOLS[@]}"; do
    if ! command -v "$tool" &>/dev/null; then
      echo "$tool is not installed, try running: $0 install"
      exit 1
    fi
  done
}

install() {
  echo "Installing Node.js packages..."
  npm install

  echo "Installing Ruby gems..."
  bundle install
}

build() {
  check
  echo "Building Jekyll site..."
  bundle exec jekyll build "$@"
}

test() {
  check

  echo "Cleaning Jekyll site..."
  bundle exec jekyll clean

  echo "Serving Jekyll site..."
  bundle exec jekyll serve --watch "$@"
}

# Periksa apakah setidaknya satu argumen disediakan
if [ "$#" -lt 1 ]; then
  echo "Usage: $0 {install|build|test} [optional args...]"
  exit 1
fi

COMMAND=$1
shift

case "$COMMAND" in
install)
  install
  ;;
build)
  build "$@"
  ;;
test)
  test "$@"
  ;;
*)
  echo "Unknown command: $COMMAND"
  exit 1
  ;;
esac
